DROP TABLE IF EXISTS VehicleOwner;
DROP TABLE IF EXISTS ChargerOwner;
DROP TABLE IF EXISTS Account;

CREATE TABLE Account(
    id INT AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    username VARCHAR(50) NOT NULL,
    passwordHashed VARCHAR(255),
    email VARCHAR(100) NOT NULL UNIQUE,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE VehicleOwner(
    id INT AUTO_INCREMENT PRIMARY KEY,
    accountId INT NOT NULL,
    FOREIGN KEY (accountId) REFERENCES Account(id) ON DELETE CASCADE
);

CREATE TABLE ChargerOwner(
    id INT AUTO_INCREMENT PRIMARY KEY,
    accountId INT NOT NULL,
    FOREIGN KEY (accountId) REFERENCES Account(id) ON DELETE CASCADE
);